name: New issue triage
on:
  issues:
    types:
      - opened

permissions: {}

jobs:
  issue_cleanup:
    name: Clean issue body
    uses: mui/mui-public/.github/workflows/issues_body-cleanup.yml@530ec94f97bfe64ae018a9fd8ff0c326cbd61298
    permissions:
      contents: read
      issues: write
